### ISSUE TITLE
环境都装好了也都装对了，但训练的时候出错了，报错如下

### ISSUE THREAD

**Issue by Laulen** [KyanChen/RSMamba#14]
$ python tools/train.py configs/rsmamba/rsmamba_aid_b.py  
/home/wangweijun/.conda/envs/rsmamba2/lib/python3.11/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/conda/conda-bld/pytorch_1702400430266/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/data/wangweijun/zhangqianqian/RSMamba/tools/train.py", line 164, in <module>
    main()
  File "/data/wangweijun/zhangqianqian/RSMamba/tools/train.py", line 145, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangweijun/.local/lib/python3.11/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
                                        ^^^^^^^^^^^^^^^^^^
  File "/home/wangweijun/.local/lib/python3.11/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/home/wangweijun/.local/lib/python3.11/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
                                           ^^^^^^^^^^^^^^^^^^
  File "/home/wangweijun/.local/lib/python3.11/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/home/wangweijun/.local/lib/python3.11/site-packages/mmengine/config/config.py", line 925, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "/data/wangweijun/zhangqianqian/RSMamba/configs/rsmamba/_base_/datasets/aid_bs64_pil_resize_autoaug.py", line 19, in <module>
    scale=img_size,
          ^^^^^^^^
<img width="1058" alt="2024-06-12 181241" src="https://github.com/KyanChen/RSMamba/assets/53033753/1f0f8e5e-0b1a-495e-8e53-8a9f03bb3f27">

NameError: name 'img_size' is not defined

**Comment by kcarol1** [comment]
nwpu_bs64_pil_resize_autoaug.py
nwpu_dataset.py
这两个配置文件自己改一下进行了

**Comment by clear1oveZ** [comment]
> nwpu_bs64_pil_resize_autoaug.py nwpu_dataset.py 这两个配置文件自己改一下进行了
你好，我也是这个问题，怎么改呢？这个img_size是怎么定义的？是什么参数呢？

**Comment by KyanChen** [comment]
已修改 img_size = 224
